default_language_version:
  python: python3

exclude: ^$|instrument/

ci:
  autofix_prs: true

repos:
  # Run fast code improvement/checks before running PR specific helpers.
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
        args: ['--maxkb=4096']
      - id: end-of-file-fixer
